version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11

  build:
    commands:
      - echo Skipping tests and building `date`
      - mvn install package -DskipTests  # Skips tests during the build

  post_build:
    commands:
      - echo Build completed at `date`

artifacts:
  files:
    - target/my-java-app-1.0-SNAPSHOT.jar
